SELECT C.N_NAME, sum(A.L_QUANTITY)
FROM ORDERS D 
LEFT OUTER JOIN LINEITEM A ON (A.L_ORDERKEY = D.O_ORDERKEY)
LEFT OUTER JOIN CUSTOMER E ON (D.O_CUSTKEY = E.C_CUSTKEY)
LEFT OUTER JOIN NATION C ON (C.N_NATIONKEY = E.C_NATIONKEY)
GROUP BY C.N_NATIONKEY
HAVING sum(A.L_QUANTITY) > 62000
ORDER BY sum(A.L_QUANTITY) DESC;